[package]
name = "ecsact_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
ecsact = { path = "../ecsact" }
proc-macro2 = "1.0.49"
quote = "1.0.21"
syn = "1.0.105"

[build-dependencies]

