[package]
name = "ecsact_rtb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
bindgen = "0.63.0"
pathdiff = "0.2.1"

