[package]
name = "ecsact_codegen"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.49"
quote = "1.0.21"
syn = "1.0.105"

[build-dependencies]
quote = "1.0.21"

