[package]
name = "ecsact_dylib_runtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]
bench = false

[dependencies]
ecsact = { path = "../ecsact" }

[build-dependencies]
bindgen = "0.53.1"
cc = "1.0.78"
json = "0.12.4"

