[package]
name = "ecsact_env"
version = "0.1.0"
edition = "2021"

[features]
cargo = []
default = ["cargo"]

[dependencies]
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"

