name: Release

on:
  release:
    types: [published]

jobs:
  windows-release:
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            /Users/runneradmin/AppData/Local/bazelisk
            /Users/runneradmin/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v3
      - run: bazel sync --config=ci --only=crate_index
        env: {CARGO_BAZEL_REPIN: 'true'}
      - run: bazel build --config=ci -c opt //ecsact_rust_codegen:ecsact_rust_codegen_bin
      - uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: bazel-bin/ecsact_rust_codegen/ecsact_rust_codegen_bin.dll

  linux-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v3
      - run: bazel sync --config=ci --only=crate_index
        env: {CARGO_BAZEL_REPIN: 'true'}
      - run: bazel build --config=ci -c opt //ecsact_rust_codegen:ecsact_rust_codegen_bin
      - run: cp bazel-bin/ecsact_rust_codegen/libecsact_rust_codegen_bin.so ecsact_rust_codegen_bin.so
      - uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: ecsact_rust_codegen_bin.so

